import { sidebar } from "vuepress-theme-hope";

export const zhSidebar = sidebar({
  "/zh/": [
    "", 
     "Products/",
    {
      text: "产品中心",
      icon: "lightbulb",
      prefix: "Products/",
      children: [
        "Processorclass/",
        "Storageclass/",
        "Analog/",
        "Communication/",
        "Sensorclass/", 
      ],
      
    }, 
     "TechLearn/",
    {
      text: "技术资料",
      icon: "lightbulb",
      prefix: "TechLearn/",
      children: [ "Book/",
      ],
    },   
      "Solutions/",
    {
      text: "服务方案",
      icon: "lightbulb",
      prefix: "Solutions/",
      children: [ 
      ],
    }, 
     "Cases/",
    {
      text: "合作案例",
      icon: "lightbulb",
      prefix: "Cases/",
      children: "structure",
    }, 
    // {
    //   text: "产品中心",
    //   icon: "laptop-code",
    //   prefix: "Products/",
    //   link: "Products/",
    //   children: "structure",
    // },
    // {
    //   text: "服务方案",
    //   icon: "laptop-code",
    //   prefix: "Solutions/",
    //   link: "Solutions/",
    //   children: "structure",
    // },
    // {
    //   text: "技术资料",
    //   icon: "laptop-code",
    //   prefix: "TechLearn/",
    //   link: "TechLearn/",
    //   children: "structure",
    // },
    // {
    //   text: "合作案例",
    //   icon: "laptop-code",
    //   prefix: "Cases/",
    //   link: "Cases/",
    //   children: "structure",
    // }, 
    // {
    //   text: "关于我们",
    //   icon: "laptop-code",
    //   prefix: "AboutUs/",
    //   link: "AboutUs/",
    //   children: "structure",
    // }, 
    // {
    //   text: "联系我们",
    //   icon: "laptop-code",
    //   prefix: "Contact/",
    //   link: "Contact/",
    //   children: "structure",
    // },
    // {
    //   text: "获取报价",
    //   icon: "laptop-code",
    //   prefix: "CTA/",
    //   link: "CTA/",
    //   children: "structure",
    // }, 
    // {
    //   text: "文章",
    //   icon: "book",
    //   prefix: "posts/",
    //   children: "structure",
    // },
    // "intro",
    // {
    //   text: "幻灯片",
    //   icon: "person-chalkboard",
    //   link: "https://ecosystem.vuejs.press/zh/plugins/markdown/revealjs/demo.html",
    // },
  ],
  "/zh/Products/": "structure",
  "/zh/Solutions/": "structure",
  "/zh/TechLearn/": "structure",
  "/zh/Cases/": "structure",
  "/zh/AboutUs/": "structure",
  "/zh/Contact/": "structure",
  "/zh/CTA/": "structure",
  // "/zh/posts/": "structure", 
});
